### ISSUE TITLE
About training data annotation

### ISSUE THREAD

**Issue by huzheyuan740** [weigao95/kPAM#1]
Hi! Nice work! After reading your paper, I noticed that the data annotation method you used is similar to LabelFusion. I used LabelFusion annotation tool before. If I want to collect my own dataset, can I make appropriate modifications based on LabelFusion to make the annotation data suitable for network training?

**Comment by weigao95** [comment]
Sorry for the delayed reply. 

Yes, you can modify the annotation tool used in LabelFusion to annotate the keypoint. Essentially you need to save the keypoint when doing keypoint assisted registration in labelfusion.

**Comment by huzheyuan740** [comment]
@weigao95 Thank you for your reply! I will try it. Meanwhile,when I annotate the keypoints, do I need the complete object meshes as well? Or could you provide part of your training data so that I can know the format of the data.Thank you in advance!

**Comment by weigao95** [comment]
The object mesh is not necessary. In our implementation, we perform a 3D reconstruction and annotate the reconstructed mesh.

The training data is the same as the [dense object net](https://github.com/RobotLocomotion/pytorch-dense-correspondence/blob/master/doc/data_organization.md) project, and you can follow the instruction of that project to set it up.

The data from dense object net has object annotation but not keypoint annotation. You need to annotate them to train the keypoint network.

**Comment by iamlucaswolf** [comment]
Hey @weigao95 

thank you for providing this great work. 

Quick question regarding annotation: How did you annotate keypoints that are not on the object surface (e.g. the top center of mugs)? LabelFusion - as far as I understand it - only allows placing keypoints by raycasting onto the nearest point vertex, and points are seemingly immovable after placing them...
